services:
  data-generator:
    container_name: quantum-circiut-runner
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    volumes:
      - ./gen/:/usr/src/quantum-data-generator/gen/
    environment:
      IBM_RUNTIME_CHANNEL: ${IBM_RUNTIME_CHANNEL}
      IBM_RUNTIME_INSTANCE: ${IBM_RUNTIME_INSTANCE}
      IBM_RUNTIME_TOKEN: ${IBM_RUNTIME_TOKEN}
