services:
  data-generator:
    container_name: quantum-circiut-runner
    build:
      context: .
      dockerfile: Dockerfile
    # for now its testing setup
    # restart: always
    volumes:
      - ./gen/:/usr/src/quantum-data-generator/gen/
