DEFAULTS = {
    'basis_set': 'sto3g',
    'ansatz_reps': 2,
    'local': True,
    'ibm_quantum': False,
    'max_iterations': 100,
    'convergence_threshold_enable': False,
    'convergence_threshold': 1e-6,
    'optimizer': 'COBYLA',
    'shots': 1024,
    'optimization_level': 1,
    'kafka': {
        'server': 'localhost:9092',
        'topic': 'vqe_results',
        'retries': 3,
        'internal_retries': 0,
        'acks': 'all',
        'timeout': 10,
    },
}
