global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['prometheus-pushgateway:9091']
    scrape_interval: 30s
    honor_labels: true

  - job_name: 'quantum-pipeline-cpu'
    static_configs:
      - targets: ['quantum-pipeline-cpu:8000']  # If app exposes metrics
    scrape_interval: 30s

  - job_name: 'quantum-pipeline-gpu'
    static_configs:
      - targets: ['quantum-pipeline-gpu:8000']  # If app exposes metrics
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
    metrics_path: '/minio/v2/metrics/cluster'