FROM apache/airflow:2.10.5

# install java
USER root
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
USER airflow

COPY . .
RUN pip install --no-cache-dir ".[airflow]"
