"""Canonical input contract shared by the ML modules.

Both predictors consume Iceberg table `ml_iteration_features` (generated by
`docker/airflow/scripts/quantum_ml_feature_processing.py`). Its `converged` column is
the optimizer's `success` flag, not agreement with a reference energy: it says SciPy
terminated successfully, nothing about accuracy.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Iterable

RUN_KEY = 'experiment_id'
"""Column identifying one VQE run in `ml_iteration_features`."""

FIRST_ITERATION = 1
"""First `iteration_step` of a run; `VQESolver.current_iter` starts at 1."""

# Fixtures for synthetic development data; the energies are curve shapes, not benchmarks.
SYNTHETIC_MOLECULES: list[dict[str, Any]] = [
    {'name': 'H2', 'num_qubits': 4, 'e_fci': -1.1175, 'e_local': -0.78},
    {'name': 'LiH', 'num_qubits': 12, 'e_fci': -7.882, 'e_local': -7.50},
    {'name': 'H2O', 'num_qubits': 14, 'e_fci': -75.012, 'e_local': -74.60},
    {'name': 'NH3', 'num_qubits': 16, 'e_fci': -55.521, 'e_local': -55.10},
    {'name': 'N2', 'num_qubits': 20, 'e_fci': -107.660, 'e_local': -107.20},
]


def default_molecules() -> list[dict[str, Any]]:
    """Fresh copy of `SYNTHETIC_MOLECULES`, safe for callers to mutate."""
    return [dict(spec) for spec in SYNTHETIC_MOLECULES]


def require_columns(df_columns: Iterable[str], required: set[str], argument: str) -> None:
    """Raise `ValueError` naming any of `required` missing from `df_columns`.

    Args:
        df_columns: Column names, typically `df.columns`.
        required: Column names the caller cannot proceed without.
        argument: Parameter name to quote in the error, e.g. `'df_iter'`.

    Raises:
        ValueError: If any required column is absent.
    """
    missing = required - set(df_columns)
    if missing:
        raise ValueError(f'{argument} missing required columns: {sorted(missing)}')
