name: Build and Test Docker Images
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        dockerfile: [cpu, gpu]
        include:
          - dockerfile: cpu
            display_name: "CPU"
          - dockerfile: gpu
            display_name: "GPU"
    outputs:
      image_cpu: ${{ matrix.dockerfile == 'cpu' && steps.image_info.outputs.image_tag || '' }}
      image_gpu: ${{ matrix.dockerfile == 'gpu' && steps.image_info.outputs.image_tag || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest and remove dependencies
        run: |
          python -m pytest
          pip freeze | grep -v "^-e" | xargs pip uninstall -y

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.dockerfile }}-latest
            type=ref,event=branch,suffix=-${{ matrix.dockerfile }}
            type=sha,prefix=${{ matrix.dockerfile }}-
            type=raw,value=pr-${{ github.event.pull_request.number }}-${{ matrix.dockerfile }},enable=${{ github.event_name == 'pull_request' }}

      - name: Build the ${{ matrix.display_name }} Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.dockerfile }}
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Store single image tag for later use
        id: image_info
        run: |
          TAGS_ARRAY=(${{ steps.meta.outputs.tags }})
          FIRST_TAG="${TAGS_ARRAY[0]}"
          echo "image_tag=${FIRST_TAG}" >> $GITHUB_OUTPUT

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.image_info.outputs.image_tag }}
          format: 'sarif'
          output: 'trivy-results-${{ matrix.dockerfile }}.sarif'
          severity: 'CRITICAL,HIGH'
          timeout: '10m' # Longer timeout to ensure scan completes

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: always() && github.event_name != 'pull_request'
        with:
          sarif_file: 'trivy-results-${{ matrix.dockerfile }}.sarif'
          category: 'trivy-${{ matrix.dockerfile }}'
